// ExportBank2Functions - Batch decompile all functions in the Bank 2 (Flash2) address range
// Exports decompiled C to a single file for offline analysis and naming campaigns
// Bank 2 range: 0x00500000 - 0x0053DFFF
// @author kuminz-re
// @category Analysis
// @keybinding
// @menupath
// @toolbar

import ghidra.app.script.GhidraScript;
import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressSet;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.FunctionManager;
import ghidra.util.task.TaskMonitor;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class ExportBank2Functions extends GhidraScript {

    private static final long BANK2_START = 0x00500000L;
    private static final long BANK2_END   = 0x0053DFFFL;

    @Override
    public void run() throws Exception {
        String[] args = getScriptArgs();
        String outputFile = args.length > 0 ? args[0] : "/tmp/bank2_functions.cpp";

        println("======================================================================");
        println("EXPORT BANK 2 FUNCTIONS");
        println("======================================================================");
        println("");
        println("Address range: 0x" + Long.toHexString(BANK2_START) +
                " - 0x" + Long.toHexString(BANK2_END));
        println("Output file:   " + outputFile);
        println("");

        FunctionManager fm = currentProgram.getFunctionManager();
        Address rangeStart = toAddr(BANK2_START);
        Address rangeEnd   = toAddr(BANK2_END);
        AddressSet bank2Range = new AddressSet(rangeStart, rangeEnd);

        List<Function> funcs = new ArrayList<>();
        FunctionIterator iter = fm.getFunctions(bank2Range, true);
        while (iter.hasNext()) {
            funcs.add(iter.next());
        }
        Collections.sort(funcs, (a, b) -> a.getEntryPoint().compareTo(b.getEntryPoint()));

        println("Found " + funcs.size() + " functions in Bank 2");
        println("");

        DecompInterface decompiler = new DecompInterface();
        DecompileOptions options = new DecompileOptions();
        decompiler.setOptions(options);
        decompiler.toggleCCode(true);
        decompiler.toggleSyntaxTree(true);
        decompiler.setSimplificationStyle("decompile");

        if (!decompiler.openProgram(currentProgram)) {
            println("ERROR: Failed to initialize decompiler");
            return;
        }

        int exported = 0;
        int failed = 0;

        try (FileWriter writer = new FileWriter(outputFile)) {
            writer.write("// Bank 2 (Flash2) Function Export — CM848 S90140.06\n");
            writer.write("// Range: 0x00500000 - 0x0053DFFF\n");
            writer.write("// Functions: " + funcs.size() + "\n");
            writer.write("// Generated by ExportBank2Functions.java\n\n");

            for (Function func : funcs) {
                String addr = String.format("0x%08x", func.getEntryPoint().getOffset());
                String name = func.getName();

                writer.write("//\n");
                writer.write("// Function: " + name + " @ " + addr + "\n");
                writer.write("//\n\n");

                try {
                    DecompileResults results = decompiler.decompileFunction(
                            func, 60, TaskMonitor.DUMMY);

                    if (results != null && results.decompileCompleted()) {
                        writer.write(results.getDecompiledFunction().getC());
                        writer.write("\n\n");
                        exported++;
                    } else {
                        String err = results != null ? results.getErrorMessage() : "null results";
                        writer.write("/* DECOMPILE FAILED: " + err + " */\n\n");
                        failed++;
                    }
                } catch (Exception e) {
                    writer.write("/* EXCEPTION: " + e.getMessage() + " */\n\n");
                    failed++;
                }

                if (exported % 50 == 0 && exported > 0) {
                    println("  Decompiled " + exported + " functions...");
                }
            }
        } finally {
            decompiler.dispose();
        }

        println("======================================================================");
        println("EXPORT COMPLETE!");
        println("  Decompiled: " + exported);
        println("  Failed:     " + failed);
        println("  Output:     " + outputFile);
        println("======================================================================");
    }
}
