using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: TypeLibVersion(1, 0)]
[assembly: ImportedFromTypeLib("ASSEMBLERLib")]
[assembly: Guid("2d66c7b5-4803-11d7-a532-0008a1326f46")]
[assembly: PrimaryInteropAssembly(1, 0)]
[assembly: AssemblyVersion("3.0.5.17102")]
namespace Cummins.Interop.Assembler;

[Guid("ADA110A6-50FA-4DBE-893E-296531B75324")]
public enum AssemblerMsgEnum
{
	ERR_ID_INVALID_INPUT_CONFIGURATION = 1001,
	ERR_ID_INPUT_CONFIGURATION_NOT_AVAILABLE = 1002,
	ERR_ID_UNSUPPORTED_GTIS_LEVEL = 1003,
	ERR_ID_INVALID_GTIS_LEVEL = 1004,
	ERR_ID_TABLE_EXCEED_BLOCK_BOUNDARIES = 1011,
	ERR_ID_UNABLE_TO_READ_DATA_FROM_SUBFILE = 1012,
	ERR_ID_DATAPLATE_REC_IS_INVALID = 1013,
	ERR_ID_UNABLE_TO_SET_CURRENT_IMAGE_INDEX = 1014,
	ERR_ID_UNABLE_TO_ADD_IMAGE_TO_CALBINIMAGE_COMPONENT = 1015,
	ERR_ID_INVALID_INPUT_DTD = 1021,
	ERR_ID_INVALID_TOOL_FAMILY = 1022,
	ERR_ID_INVALID_SUBFILE_TYPE = 1023,
	ERR_ID_INVALID_WORDSIZE = 1024,
	ERR_ID_INVALID_BYTEORDER = 1025,
	ERR_ID_INVALID_PRODUCT_IDENTIFIER = 1026,
	ERR_ID_TOOL_FAMILY_TAG_ABSENT = 1027,
	ERR_ID_BYTE_ORDER_TAG_ABSENT = 1028,
	ERR_ID_PROD_ID_TAG_ABSENT = 1029,
	ERR_ID_GTIS_LEVEL_TAG_ABSENT = 1030,
	ERR_ID_WORD_SIZE_TAG_ABSENT = 1031,
	ERR_ID_DATAPLATEFIELDS_TAG_ABSENT = 1032,
	ERR_ID_UPDATE_RELEASE_LEVEL_VALUE_IS_INVALID = 1033,
	ERR_ID_HEADERFILE_TAG_ABSENT = 1034,
	ERR_ID_SUBFILELIST_TAG_ABSENT = 1035,
	ERR_ID_SUBFILE_TAG_ABSENT = 1036,
	ERR_ID_SUBFILENUMBER_TAG_ABSENT = 1037,
	ERR_ID_PATHNAME_TAG_ABSENT = 1038,
	ERR_ID_PRODUCTINFO_TAG_ABSENT = 1039,
	ERR_ID_DATAPLATE_NAME_TAG_ABSENT = 1040,
	ERR_ID_OUTPUT_CALIBRATION_FILE_NOT_AVAILABLE = 1164,
	ERR_ID_UNABLE_TO_READ_INDEX_TABLE = 1041,
	ERR_ID_UNABLE_TO_READ_ROM_DATE_VERSION = 1042,
	ERR_ID_UNABLE_TO_CREATE_SUBFILE_COMPONENT = 1043,
	ERR_ID_UNABLE_TO_READ_PRODUCTID = 1044,
	ERR_ID_SUBFILE_WRONG_PRODUCTID = 1045,
	ERR_ID_CODE_SUBFILE_NOT_PRESENT = 1046,
	ERR_ID_NOT_AUTHORIZED_TO_PERFORM_ASSEMBLY = 1047,
	ERR_ID_SUBFILE_WRONG_TYPE = 1048,
	ERR_ID_UNABLE_TO_READ_CREC = 1049,
	ERR_ID_UNABLE_TO_READ_SUBFILE_RELEALSE_LEVEL = 1050,
	ERR_ID_UNABLE_TO_READ_BDSREC = 1051,
	ERR_ID_UNABLE_TO_READ_SUBFILE = 1052,
	ERR_ID_UNABLE_TO_UPDATE_RELEASE_OF_SUBFILE = 1053,
	ERR_ID_UNABLE_TO_SET_CRC_OF_SUBFILE = 1054,
	ERR_ID_UNABLE_TO_SET_GROUP_NUMBER_IN_SUBFILE_COMPONENT = 1055,
	ERR_ID_SUBFILE_IS_NOT_RELEASED = 1056,
	ERR_ID_WRONG_PRODID_ASCII_HEADER_RECORDS = 1057,
	ERR_ID_WRONG_PRODID_COMPATIBILITY_HEADER_RECORDS = 1058,
	ERR_ID_INVALID_BDS_LENGTH = 1059,
	ERR_ID_UNABLE_TO_GEN_ASCII_HDR_XML_FORMAT = 1061,
	ERR_ID_UNABLE_TO_CREATE_CALBINIMAGE_COMPONENT = 1062,
	ERR_ID_SUBFILE_INCOMPATIBLE_DATEVERSION = 1063,
	ERR_ID_UNABLE_TO_WRITE_OUTPUT_CALIBRATION_FILE = 1064,
	ERR_ID_UNABLE_TO_SET_GROUP_NUMBER_IN_CALBINIMAGE_COMPONENT = 1065,
	ERR_ID_INVALID_OPTION_TYPE = 1066,
	ERR_ID_NO_VALUE_TAG_PRESENT = 1067,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_VALUE_TAG = 1068,
	ERR_ID_NO_MAXSTRINGLENGTH_TAG_PRESENT = 1069,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_MAXSTRINGLENGTH_TAG = 1070,
	ERR_ID_NO_ITN_TAG_PRESENT = 1071,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_ITN_TAG = 1072,
	ERR_ID_INVALID_ITN_VALUE = 1073,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_HEXBINARYVALUE = 1074,
	ERR_ID_NO_OPTIONTYPE_TAG_PRESENT = 1075,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_OPTIONTYPE_TAG = 1076,
	ERR_ID_NO_OPTIONNUMBER_TAG_PRESENT = 1077,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_OPTIONNUMBER_TAG = 1078,
	ERR_ID_PARTNNUMBER_TAG_ABSENT = 1079,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_PARTNUMBER_TAG = 1080,
	ERR_ID_UNSUPPORTED_ITN_VALUE = 1081,
	ERR_ID_INCORRECT_SIZE_OF_PRODSTRUCTOPT = 1082,
	EER_ID_INVALID_ENGINE_BUILD_DATE = 1083,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_HARNESSKEYECMINSTANCE = 1084,
	ERR_ID_INSTANCE_VALUE_IS_TOO_LARGE_FOR_GIVEN_MASK = 1085,
	ERR_ID_HARNESSKEYCOMPATIBILITYLIST_CANNOT_BE_SET = 1086,
	ERR_ID_NO_COMPATIBILITY_HEADER_TAG_PRESENT = 1087,
	ERR_ID_UNABLE_TO_CREATE_CHILD_NODE = 1088,
	ERR_ID_UNABLE_TO_APPEND_NODE_TO_COMPATIBILITYHEADER = 1089,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_USING_PARITY = 1090,
	ERR_ID_NO_HARNESSKEYECMINSTANCE_TAG_PRESENT = 1091,
	ERR_ID_NO_USINGPARITY_TAG_PRESENT = 1092,
	ERR_ID_INVALID_VALUE_OF_USINGPARITY_VALUE_PRESENT = 1093,
	ERR_ID_NO_HARNESSKEYECMINSTANCE_VALUE_PRESENT = 1094,
	ERR_ID_INVALID_VALUE_OF_HARNESSKEYECMINSTANCE = 1095,
	ERR_ID_UNABLE_TO_ACCESS_COMPATIBILITY_HEADER_RECORD = 1096,
	ERR_ID_WRITING_BEYOND_DATABLOCK = 1097,
	ERR_ID_READING_BEYOND_DATABLOCK = 1098,
	ERR_ID_INVALID_COMMAND_RECORD = 1101,
	ERR_ID_WRITING_BEYOND_TABLE_BOUNDARY = 1102,
	ERR_ID_DETECTED_HOLE_IN_A_TABLE = 1103,
	ERR_ID_ATEMPT_TO_OVERWRITE_DATA = 1104,
	ERR_ID_INVALID_RECORD_ENCOUNTER = 1105,
	ERR_ID_INVALID_TABLE_RECORD = 1165,
	ERR_ID_DETECTED_HOLE_BETWEEN_TABLES = 1106,
	ERR_ID_DATA_OVERLAP_FOUND = 1111,
	ERR_ID_UNABLE_TO_CREATE_SAFEARRAY = 1112,
	ERR_ID_WRITING_BEYOND_BLOCK = 1113,
	ERR_ID_READING_BITSET_BEYOND_SEQUENCE = 1121,
	ERR_ID_WRITING_BITSET_BEYOND_SEQUENCE = 1122,
	ERR_ID_NO_BLOCK_FOUND = 1131,
	ERR_ID_INVALID_OR_OVERLAP_BLOCK_ADDRESS = 1132,
	ERR_ID_INDEX_OUT_OF_BOUND = 1133,
	ERR_ID_INVALID_POINTER = 1141,
	ERR_ID_UNABLE_TO_ALLOCATE_MEMORY = 1142,
	ERR_ID_OUT_PARAMETER_NULL = 1143,
	ERR_ID_UNABLE_TO_READ_CALIBRATION_FILE = 1151,
	ERR_ID_UNABLE_TO_OPEN_INPUT_CALIBRATION_FILE = 1152,
	ERR_ID_UNABLE_TO_SET_STRINGVALUEIN_DATAPLATE = 1153,
	ERR_ID_UNABLE_TO_SET_HEXBINARYVALUEIN_DATAPLATE = 1154,
	ERR_ID_UNABLE_TO_ACCESS_ADDRESS_OF_INDEX_TABLE = 1155,
	ERR_ID_UNABLE_TO_SET_PRODSTRUCTOPTIONVALUEINDATAPLATE = 1156,
	ERR_ID_UNABLE_TO_SET_ENGINE_BUILD_DATE = 1157,
	ERR_ID_UNABLE_TO_GET_CALIBRATIONFILE_NAME = 1158,
	ERR_ID_INVALID_DATAPLATE_TYPE = 1159,
	ERR_ID_INVALID_PART_NUMBER = 1160,
	ERR_ID_DATAPLATE_NAME_NOT_PRESENT = 1161,
	ERR_ID_CALIBRATION_TAG_ABSENT = 1162,
	ERR_ID_INVALID_ITN_VALUE_IN_DATAPLATE = 1163,
	ERR_ID_INVALID_HEXBINARYVALUE = 1330,
	ERR_ID_UNABLE_TO_OPEN_HEADERFILE = 1400,
	ERR_ID_INVALID_HEADERFILE_CRC = 1401,
	ERR_ID_INCOMPATIBLE_HEADER_RECORDS = 1402,
	ERR_ID_INVALID_HEADER_LINE_LEN = 1403,
	ERR_ID_INVALID_INDEX_TABLE_NUMBER = 1404,
	ERR_ID_INVALID_INDEX_TABLE = 1405,
	ERR_ID_INVALID_INDEX_TABLE_LENGTH = 1406,
	ERR_ID_UNABLE_TO_GENERATE_CHECKSUM = 1407,
	ERR_ID_NO_INPUT_HEADER_FILE = 1408,
	ERR_ID_UNABLE_TO_SET_HDR_RECORD_IN_OUTPUT_CALIBRATION = 1409,
	ERR_ID_UNABLE_TO_PROCESS_HDR_RECORD = 1410,
	ERR_ID_DATAPLATE_OPTION_TAG_ABSENT = 1430,
	ERR_ID_UNABLE_TO_PROCESS_HEADER_RECORD = 1501,
	ERR_ID_UNABLE_TO_RETRIEVE_RECORD_TYPE = 1502,
	ERR_ID_UNABLE_TO_RETRIEVE_DESTINATION_ITN = 1503,
	ERR_ID_UNABLE_TO_RETRIEVE_OFFSET = 1504,
	ERR_ID_UNABLE_TO_FETCH_HEADER_INFO_FROM_HEADER_RECORD = 1505,
	ERR_ID_UNABLE_TO_RETRIEVE_RECORD_LENGTH = 1506,
	PROGRESS_ID_ASSEMBLY_HAS_BEGUN = 1201,
	PROGRESS_ID_VALIDATE_INPUT = 1202,
	PROGRESS_ID_READ_SUBFILE = 1203,
	PROGRESS_ID_CREATE_BLOCK = 1204,
	PROGRESS_ID_LOAD_INDEX_TABLE = 1205,
	PROGRESS_ID_SET_DATA_PLATE = 1206,
	PROGRESS_ID_ASSEMBLY_COMPLETE = 1207,
	PROGRESS_ID_WRITING_ASSEMBLY_TO_CALIBRATION_FILE = 1208,
	PROGRESS_ID_OUTPUT_CALIBRATION_WRITTEN = 1209,
	PROGRESS_ID_LOAD_SUBFILES_USING_SBUFILECOMPONENT = 1210,
	PROGRESS_ID_VALIDATE_INPUT_SUBFILES = 1211,
	PROGRESS_ID_READ_TABLE_COMMAND_RECORD = 1212,
	PROGRESS_ID_READ_DATA_RECORDS = 1213,
	PROGRESS_ID_LOAD_CALFILE_USING_CALBINCOMPONENT = 1214,
	PROGRESS_ID_READING_INDEX_TABLE = 1215,
	PROGRESS_ID_WRITING_INVALID_OPTION_PART_NO = 1216,
	PROGRESS_ID_INC_READ_VALIDATE_INPUT_CONFIGURATION = 1301,
	PROGRESS_ID_INC_READ_SUBFILE_USING_SUBFILE_COMPONENT = 1302,
	PROGRESS_ID_INC_VALIDATE_SUBFILE_AGAINST_INPUT_CONFIGURATION = 1303,
	PROGRESS_ID_INC_READ_TABLE_COMMAND_RECORDS = 1304,
	PROGRESS_ID_INC_READ_DATA_RECORDS = 1305,
	PROGRESS_ID_INC_CREATE_INDEX_TABLE = 1306,
	PROGRESS_ID_INC_CREATE_BDS = 1307,
	PROGRESS_ID_INC_SET_DATAPLATE = 1308,
	PROGRESS_ID_INC_WRITE_TABLE_INTO_BLOCK = 1309,
	PROGRESS_ID_INC_OUTPUT_CALIBRATION_FILE = 1310,
	PROGRESS_ID_INC_READ_CALFILE_USING_CALBINCOMPONENT = 1311,
	PROGRESS_ID_INC_READ_INDEX_TABLE = 1312,
	PROGRESS_ID_INC_WRITING_ASSEMBLY = 1313,
	ERR_ID_INVALID_HEADER_FILE_FORMAT = 1507
}
public enum tagAssemblerMsgEnum
{
	ERR_ID_INVALID_INPUT_CONFIGURATION = 1001,
	ERR_ID_INPUT_CONFIGURATION_NOT_AVAILABLE = 1002,
	ERR_ID_UNSUPPORTED_GTIS_LEVEL = 1003,
	ERR_ID_INVALID_GTIS_LEVEL = 1004,
	ERR_ID_TABLE_EXCEED_BLOCK_BOUNDARIES = 1011,
	ERR_ID_UNABLE_TO_READ_DATA_FROM_SUBFILE = 1012,
	ERR_ID_DATAPLATE_REC_IS_INVALID = 1013,
	ERR_ID_UNABLE_TO_SET_CURRENT_IMAGE_INDEX = 1014,
	ERR_ID_UNABLE_TO_ADD_IMAGE_TO_CALBINIMAGE_COMPONENT = 1015,
	ERR_ID_INVALID_INPUT_DTD = 1021,
	ERR_ID_INVALID_TOOL_FAMILY = 1022,
	ERR_ID_INVALID_SUBFILE_TYPE = 1023,
	ERR_ID_INVALID_WORDSIZE = 1024,
	ERR_ID_INVALID_BYTEORDER = 1025,
	ERR_ID_INVALID_PRODUCT_IDENTIFIER = 1026,
	ERR_ID_TOOL_FAMILY_TAG_ABSENT = 1027,
	ERR_ID_BYTE_ORDER_TAG_ABSENT = 1028,
	ERR_ID_PROD_ID_TAG_ABSENT = 1029,
	ERR_ID_GTIS_LEVEL_TAG_ABSENT = 1030,
	ERR_ID_WORD_SIZE_TAG_ABSENT = 1031,
	ERR_ID_DATAPLATEFIELDS_TAG_ABSENT = 1032,
	ERR_ID_UPDATE_RELEASE_LEVEL_VALUE_IS_INVALID = 1033,
	ERR_ID_HEADERFILE_TAG_ABSENT = 1034,
	ERR_ID_SUBFILELIST_TAG_ABSENT = 1035,
	ERR_ID_SUBFILE_TAG_ABSENT = 1036,
	ERR_ID_SUBFILENUMBER_TAG_ABSENT = 1037,
	ERR_ID_PATHNAME_TAG_ABSENT = 1038,
	ERR_ID_PRODUCTINFO_TAG_ABSENT = 1039,
	ERR_ID_DATAPLATE_NAME_TAG_ABSENT = 1040,
	ERR_ID_OUTPUT_CALIBRATION_FILE_NOT_AVAILABLE = 1164,
	ERR_ID_UNABLE_TO_READ_INDEX_TABLE = 1041,
	ERR_ID_UNABLE_TO_READ_ROM_DATE_VERSION = 1042,
	ERR_ID_UNABLE_TO_CREATE_SUBFILE_COMPONENT = 1043,
	ERR_ID_UNABLE_TO_READ_PRODUCTID = 1044,
	ERR_ID_SUBFILE_WRONG_PRODUCTID = 1045,
	ERR_ID_CODE_SUBFILE_NOT_PRESENT = 1046,
	ERR_ID_NOT_AUTHORIZED_TO_PERFORM_ASSEMBLY = 1047,
	ERR_ID_SUBFILE_WRONG_TYPE = 1048,
	ERR_ID_UNABLE_TO_READ_CREC = 1049,
	ERR_ID_UNABLE_TO_READ_SUBFILE_RELEALSE_LEVEL = 1050,
	ERR_ID_UNABLE_TO_READ_BDSREC = 1051,
	ERR_ID_UNABLE_TO_READ_SUBFILE = 1052,
	ERR_ID_UNABLE_TO_UPDATE_RELEASE_OF_SUBFILE = 1053,
	ERR_ID_UNABLE_TO_SET_CRC_OF_SUBFILE = 1054,
	ERR_ID_UNABLE_TO_SET_GROUP_NUMBER_IN_SUBFILE_COMPONENT = 1055,
	ERR_ID_SUBFILE_IS_NOT_RELEASED = 1056,
	ERR_ID_WRONG_PRODID_ASCII_HEADER_RECORDS = 1057,
	ERR_ID_WRONG_PRODID_COMPATIBILITY_HEADER_RECORDS = 1058,
	ERR_ID_INVALID_BDS_LENGTH = 1059,
	ERR_ID_UNABLE_TO_GEN_ASCII_HDR_XML_FORMAT = 1061,
	ERR_ID_UNABLE_TO_CREATE_CALBINIMAGE_COMPONENT = 1062,
	ERR_ID_SUBFILE_INCOMPATIBLE_DATEVERSION = 1063,
	ERR_ID_UNABLE_TO_WRITE_OUTPUT_CALIBRATION_FILE = 1064,
	ERR_ID_UNABLE_TO_SET_GROUP_NUMBER_IN_CALBINIMAGE_COMPONENT = 1065,
	ERR_ID_INVALID_OPTION_TYPE = 1066,
	ERR_ID_NO_VALUE_TAG_PRESENT = 1067,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_VALUE_TAG = 1068,
	ERR_ID_NO_MAXSTRINGLENGTH_TAG_PRESENT = 1069,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_MAXSTRINGLENGTH_TAG = 1070,
	ERR_ID_NO_ITN_TAG_PRESENT = 1071,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_ITN_TAG = 1072,
	ERR_ID_INVALID_ITN_VALUE = 1073,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_HEXBINARYVALUE = 1074,
	ERR_ID_NO_OPTIONTYPE_TAG_PRESENT = 1075,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_OPTIONTYPE_TAG = 1076,
	ERR_ID_NO_OPTIONNUMBER_TAG_PRESENT = 1077,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_OPTIONNUMBER_TAG = 1078,
	ERR_ID_PARTNNUMBER_TAG_ABSENT = 1079,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_PARTNUMBER_TAG = 1080,
	ERR_ID_UNSUPPORTED_ITN_VALUE = 1081,
	ERR_ID_INCORRECT_SIZE_OF_PRODSTRUCTOPT = 1082,
	EER_ID_INVALID_ENGINE_BUILD_DATE = 1083,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_HARNESSKEYECMINSTANCE = 1084,
	ERR_ID_INSTANCE_VALUE_IS_TOO_LARGE_FOR_GIVEN_MASK = 1085,
	ERR_ID_HARNESSKEYCOMPATIBILITYLIST_CANNOT_BE_SET = 1086,
	ERR_ID_NO_COMPATIBILITY_HEADER_TAG_PRESENT = 1087,
	ERR_ID_UNABLE_TO_CREATE_CHILD_NODE = 1088,
	ERR_ID_UNABLE_TO_APPEND_NODE_TO_COMPATIBILITYHEADER = 1089,
	ERR_ID_UNABLE_TO_ACCESS_VALUE_OF_USING_PARITY = 1090,
	ERR_ID_NO_HARNESSKEYECMINSTANCE_TAG_PRESENT = 1091,
	ERR_ID_NO_USINGPARITY_TAG_PRESENT = 1092,
	ERR_ID_INVALID_VALUE_OF_USINGPARITY_VALUE_PRESENT = 1093,
	ERR_ID_NO_HARNESSKEYECMINSTANCE_VALUE_PRESENT = 1094,
	ERR_ID_INVALID_VALUE_OF_HARNESSKEYECMINSTANCE = 1095,
	ERR_ID_UNABLE_TO_ACCESS_COMPATIBILITY_HEADER_RECORD = 1096,
	ERR_ID_WRITING_BEYOND_DATABLOCK = 1097,
	ERR_ID_READING_BEYOND_DATABLOCK = 1098,
	ERR_ID_INVALID_COMMAND_RECORD = 1101,
	ERR_ID_WRITING_BEYOND_TABLE_BOUNDARY = 1102,
	ERR_ID_DETECTED_HOLE_IN_A_TABLE = 1103,
	ERR_ID_ATEMPT_TO_OVERWRITE_DATA = 1104,
	ERR_ID_INVALID_RECORD_ENCOUNTER = 1105,
	ERR_ID_INVALID_TABLE_RECORD = 1165,
	ERR_ID_DETECTED_HOLE_BETWEEN_TABLES = 1106,
	ERR_ID_DATA_OVERLAP_FOUND = 1111,
	ERR_ID_UNABLE_TO_CREATE_SAFEARRAY = 1112,
	ERR_ID_WRITING_BEYOND_BLOCK = 1113,
	ERR_ID_READING_BITSET_BEYOND_SEQUENCE = 1121,
	ERR_ID_WRITING_BITSET_BEYOND_SEQUENCE = 1122,
	ERR_ID_NO_BLOCK_FOUND = 1131,
	ERR_ID_INVALID_OR_OVERLAP_BLOCK_ADDRESS = 1132,
	ERR_ID_INDEX_OUT_OF_BOUND = 1133,
	ERR_ID_INVALID_POINTER = 1141,
	ERR_ID_UNABLE_TO_ALLOCATE_MEMORY = 1142,
	ERR_ID_OUT_PARAMETER_NULL = 1143,
	ERR_ID_UNABLE_TO_READ_CALIBRATION_FILE = 1151,
	ERR_ID_UNABLE_TO_OPEN_INPUT_CALIBRATION_FILE = 1152,
	ERR_ID_UNABLE_TO_SET_STRINGVALUEIN_DATAPLATE = 1153,
	ERR_ID_UNABLE_TO_SET_HEXBINARYVALUEIN_DATAPLATE = 1154,
	ERR_ID_UNABLE_TO_ACCESS_ADDRESS_OF_INDEX_TABLE = 1155,
	ERR_ID_UNABLE_TO_SET_PRODSTRUCTOPTIONVALUEINDATAPLATE = 1156,
	ERR_ID_UNABLE_TO_SET_ENGINE_BUILD_DATE = 1157,
	ERR_ID_UNABLE_TO_GET_CALIBRATIONFILE_NAME = 1158,
	ERR_ID_INVALID_DATAPLATE_TYPE = 1159,
	ERR_ID_INVALID_PART_NUMBER = 1160,
	ERR_ID_DATAPLATE_NAME_NOT_PRESENT = 1161,
	ERR_ID_CALIBRATION_TAG_ABSENT = 1162,
	ERR_ID_INVALID_ITN_VALUE_IN_DATAPLATE = 1163,
	ERR_ID_INVALID_HEXBINARYVALUE = 1330,
	ERR_ID_UNABLE_TO_OPEN_HEADERFILE = 1400,
	ERR_ID_INVALID_HEADERFILE_CRC = 1401,
	ERR_ID_INCOMPATIBLE_HEADER_RECORDS = 1402,
	ERR_ID_INVALID_HEADER_LINE_LEN = 1403,
	ERR_ID_INVALID_INDEX_TABLE_NUMBER = 1404,
	ERR_ID_INVALID_INDEX_TABLE = 1405,
	ERR_ID_INVALID_INDEX_TABLE_LENGTH = 1406,
	ERR_ID_UNABLE_TO_GENERATE_CHECKSUM = 1407,
	ERR_ID_NO_INPUT_HEADER_FILE = 1408,
	ERR_ID_UNABLE_TO_SET_HDR_RECORD_IN_OUTPUT_CALIBRATION = 1409,
	ERR_ID_UNABLE_TO_PROCESS_HDR_RECORD = 1410,
	ERR_ID_DATAPLATE_OPTION_TAG_ABSENT = 1430,
	ERR_ID_UNABLE_TO_PROCESS_HEADER_RECORD = 1501,
	ERR_ID_UNABLE_TO_RETRIEVE_RECORD_TYPE = 1502,
	ERR_ID_UNABLE_TO_RETRIEVE_DESTINATION_ITN = 1503,
	ERR_ID_UNABLE_TO_RETRIEVE_OFFSET = 1504,
	ERR_ID_UNABLE_TO_FETCH_HEADER_INFO_FROM_HEADER_RECORD = 1505,
	ERR_ID_UNABLE_TO_RETRIEVE_RECORD_LENGTH = 1506,
	PROGRESS_ID_ASSEMBLY_HAS_BEGUN = 1201,
	PROGRESS_ID_VALIDATE_INPUT = 1202,
	PROGRESS_ID_READ_SUBFILE = 1203,
	PROGRESS_ID_CREATE_BLOCK = 1204,
	PROGRESS_ID_LOAD_INDEX_TABLE = 1205,
	PROGRESS_ID_SET_DATA_PLATE = 1206,
	PROGRESS_ID_ASSEMBLY_COMPLETE = 1207,
	PROGRESS_ID_WRITING_ASSEMBLY_TO_CALIBRATION_FILE = 1208,
	PROGRESS_ID_OUTPUT_CALIBRATION_WRITTEN = 1209,
	PROGRESS_ID_LOAD_SUBFILES_USING_SBUFILECOMPONENT = 1210,
	PROGRESS_ID_VALIDATE_INPUT_SUBFILES = 1211,
	PROGRESS_ID_READ_TABLE_COMMAND_RECORD = 1212,
	PROGRESS_ID_READ_DATA_RECORDS = 1213,
	PROGRESS_ID_LOAD_CALFILE_USING_CALBINCOMPONENT = 1214,
	PROGRESS_ID_READING_INDEX_TABLE = 1215,
	PROGRESS_ID_WRITING_INVALID_OPTION_PART_NO = 1216,
	PROGRESS_ID_INC_READ_VALIDATE_INPUT_CONFIGURATION = 1301,
	PROGRESS_ID_INC_READ_SUBFILE_USING_SUBFILE_COMPONENT = 1302,
	PROGRESS_ID_INC_VALIDATE_SUBFILE_AGAINST_INPUT_CONFIGURATION = 1303,
	PROGRESS_ID_INC_READ_TABLE_COMMAND_RECORDS = 1304,
	PROGRESS_ID_INC_READ_DATA_RECORDS = 1305,
	PROGRESS_ID_INC_CREATE_INDEX_TABLE = 1306,
	PROGRESS_ID_INC_CREATE_BDS = 1307,
	PROGRESS_ID_INC_SET_DATAPLATE = 1308,
	PROGRESS_ID_INC_WRITE_TABLE_INTO_BLOCK = 1309,
	PROGRESS_ID_INC_OUTPUT_CALIBRATION_FILE = 1310,
	PROGRESS_ID_INC_READ_CALFILE_USING_CALBINCOMPONENT = 1311,
	PROGRESS_ID_INC_READ_INDEX_TABLE = 1312,
	PROGRESS_ID_INC_WRITING_ASSEMBLY = 1313,
	ERR_ID_INVALID_HEADER_FILE_FORMAT = 1507
}
[ComImport]
[TypeLibType(4160)]
[Guid("866AEC5A-2484-11D7-A51C-0008A1326F46")]
public interface ICIAssembly
{
	[DispId(101)]
	string Configuration
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(101)]
		[return: MarshalAs(UnmanagedType.BStr)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(101)]
		[param: In]
		[param: MarshalAs(UnmanagedType.BStr)]
		set;
	}

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(104)]
	void Assemble([MarshalAs(UnmanagedType.BStr)] string bstrPath);
}
[ComImport]
[TypeLibType(4160)]
[Guid("68637035-AE08-4950-B92E-89E359DEBDE4")]
public interface ICIAssignMsgGroup
{
	[DispId(1)]
	int Group
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(1)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(1)]
		[param: In]
		set;
	}
}
[ComImport]
[ClassInterface(0)]
[Guid("F0BF7718-47FF-11D7-A532-0008A1326F46")]
[TypeLibType(2)]
public class SubfileAssemblerClass : ICIAssembly, SubfileAssembler, ICIAssignMsgGroup
{
	[DispId(101)]
	public virtual extern string Configuration
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(101)]
		[return: MarshalAs(UnmanagedType.BStr)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(101)]
		[param: In]
		[param: MarshalAs(UnmanagedType.BStr)]
		set;
	}

	public virtual extern int Group
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[param: In]
		set;
	}

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(104)]
	public virtual extern void Assemble([MarshalAs(UnmanagedType.BStr)] string bstrPath);
}
[ComImport]
[Guid("866AEC5A-2484-11D7-A51C-0008A1326F46")]
[CoClass(typeof(SubfileAssemblerClass))]
public interface SubfileAssembler : ICIAssembly
{
}
[ComImport]
[TypeLibType(2)]
[Guid("F66D6568-672B-4CAE-92D9-BDF57D9B06DA")]
[ClassInterface(0)]
public class CalibrationAssemblerClass : ICIAssembly, CalibrationAssembler, ICIAssignMsgGroup
{
	[DispId(101)]
	public virtual extern string Configuration
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(101)]
		[return: MarshalAs(UnmanagedType.BStr)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(101)]
		[param: In]
		[param: MarshalAs(UnmanagedType.BStr)]
		set;
	}

	public virtual extern int Group
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[param: In]
		set;
	}

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(104)]
	public virtual extern void Assemble([MarshalAs(UnmanagedType.BStr)] string bstrPath);
}
[ComImport]
[CoClass(typeof(CalibrationAssemblerClass))]
[Guid("866AEC5A-2484-11D7-A51C-0008A1326F46")]
public interface CalibrationAssembler : ICIAssembly
{
}
